services:
  yuris_app:
    build: .
    container_name: yuris_app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - yuris_db
    restart: unless-stopped

  yuris_db:
    image: mysql:8.0
    container_name: yuris_db
    restart: unless-stopped
    command:
      - --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --log-bin-trust-function-creators=1
    environment:
      MYSQL_DATABASE: sistema_vendas
      MYSQL_USER: yuris_user
      MYSQL_PASSWORD: yuris_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - yuris_db_data:/var/lib/mysql

volumes:
  yuris_db_data:
